const pages=["home","chat","photo","summary","test","image","promo","pro","profile","tools"];
function showPage(id){pages.forEach(p=>{const el=document.getElementById(p);if(el)el.classList.toggle('active',p===id)});window.scrollTo({top:0,behavior:'smooth'})}
function sendMessage(){const input=document.getElementById('chatInput');const text=input.value.trim();if(!text)return;const box=document.getElementById('messages');box.insertAdjacentHTML('beforeend',`<div class="message user"></div>`);box.lastElementChild.textContent=text;box.insertAdjacentHTML('beforeend',`<div class="message ai"></div>`);box.lastElementChild.textContent='Демо-ответ: я понял вопрос. На следующем этапе подключим настоящий AI, чтобы отвечать на него полноценно.';input.value='';}
document.getElementById('photoInput').addEventListener('change',e=>{const r=document.getElementById('photoResult');r.textContent=e.target.files.length?'Фото загружено. В демо-версии анализ изображения пока не подключён.':'После загрузки здесь появится демо-ответ.'});
function makeSummary(){const v=document.getElementById('summaryInput').value.trim();document.getElementById('summaryResult').textContent=v?`Демо-конспект: ${v.slice(0,180)}${v.length>180?'…':''}`:'Сначала вставь текст.'}
function makeTest(){const v=document.getElementById('testInput').value.trim();document.getElementById('testResult').innerHTML=v?`По теме «${escapeHtml(v)}» можно подготовить вопросы:<br>1. Что нужно знать по теме?<br>2. Какие основные понятия?<br>3. Какие типичные ошибки?`:'Напиши тему.'}
function makeImage(){const v=document.getElementById('imageInput').value.trim();document.getElementById('imageResult').textContent=v?`Промпт для генерации: ${v}, detailed, cinematic, high quality.`:'Опиши изображение.'}
function activatePromo(){const code=document.getElementById('promoInput').value.trim().toUpperCase();const result=document.getElementById('promoResult');const valid={WELCOME:'PRO на 7 дней',PRO7:'PRO на 7 дней',PRO30:'PRO на 30 дней'};if(valid[code]){localStorage.setItem('ushakov_pro','1');document.getElementById('plan').textContent='PRO';document.getElementById('promoStatus').textContent=valid[code];result.textContent=`Готово! Код ${code} активирован.`}else result.textContent='Код не найден.'}
function escapeHtml(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
if(localStorage.getItem('ushakov_pro')){document.getElementById('plan').textContent='PRO';document.getElementById('promoStatus').textContent='PRO активирован'}
